#!/bin/bash

# Change to project directory
cd ~/code/flask-cloud-run

# Run docker run command
docker run --rm -d --env-file ./.env -p 8080:8080 --mount type=bind,source="$(pwd)",destination=/usr/src/app flask-cloud-run
